version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: megaodds
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/megaodds
      JWT_SECRET_KEY: your-super-secret-jwt-key-change-in-production
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  postgres_data: